### ISSUE TITLE
Yandex Translate API doesn't work (ServerException:ERR_KEY_INVALID)

### ISSUE THREAD

**Issue by DanuuJI** [ogkalu2/comic-translate#160]
I have created an API key in Yandex Cloud for translate and when I input the key into app settings', I get this error when trying to translate the text.

An error occurred:
ServerException: ERR_KEY_INVALID

Traceback:
Traceback (most recent call last):
  File "D:\Utilities\comic-translate-main\app\thread_worker.py", line 30, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Utilities\comic-translate-main\pipeline.py", line 112, in translate_image
    translator.translate(self.main_page.blk_list, image, extra_context)
  File "D:\Utilities\comic-translate-main\modules\translator.py", line 163, in translate
    translation = YandexTranslator(source='auto', target=target_lang_code, api_key=self.api_key).translate(text)
  File "D:\Utilities\Python\lib\site-packages\deep_translator\yandex.py", line 137, in translate
    raise ServerException(response["code"])
deep_translator.exceptions.ServerException: ERR_KEY_INVALID

**Comment by ogkalu2** [comment]
Fixed now. You need the Folder ID and Secret Key
