### ISSUE TITLE
New Bug, any fix?

### ISSUE THREAD

**Issue by Alexamenus** [ogkalu2/comic-translate#175]
An error occurred:
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback:
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\comic-translate-main\app\thread_worker.py", line 30, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\OneDrive\Desktop\comic-translate-main\pipeline.py", line 175, in batch_process
    blk_list = self.block_detector_cache.detect(image)
  File "C:\Users\user\OneDrive\Desktop\comic-translate-main\modules\detection.py", line 24, in detect
    txt_detect_result = self.text_detection(img, device=self.device, imgsz=det_size, conf=0.2, verbose=False)[0]
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\engine\model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\engine\model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\engine\predictor.py", line 173, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\engine\predictor.py", line 239, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\nn\autobackend.py", line 735, in warmup
    self.forward(im)  # warmup
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\nn\autobackend.py", line 526, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\nn\tasks.py", line 112, in forward
    return self.predict(x, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\nn\tasks.py", line 130, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\nn\tasks.py", line 151, in _predict_once
    x = m(x)  # run
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ultralytics\nn\modules\conv.py", line 54, in forward_fuse
    return self.act(self.conv(x))
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\activation.py", line 393, in forward
    return F.silu(input, inplace=self.inplace)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\functional.py", line 2071, in silu
    return torch._C._nn.silu_(input)
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Alexamenus** [comment]
I think I can get the program to run appropriately if i uninstall l graphics drivers and reinstall them every time i open the program, but that is obviously not a fix.

**Comment by ogkalu2** [comment]
What Python Version? Also maybe you can try pip unusualling torch, torch vision and installing it again. The readme has some instructions.

**Comment by ogkalu2** [comment]
This specifically:
pip uninstall torch torchvision
pip install torch==2.1.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html
pip install torchvision==0.16.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html

You could try the latest versions instead (e.g 2.5.1 instead of 2.1.0 for torch). cu121 means Cuda version 12.1, cu118 - Cuda 11.8 and so on. Change to fit your Cuda version.

**Comment by Alexamenus** [comment]
> This specifically: pip uninstall torch torchvision pip install torch==2.1.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html pip install torchvision==0.16.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html
> 
> You could try the latest versions instead (e.g 2.5.1 instead of 2.1.0 for torch). cu121 means Cuda version 12.1, cu118 - Cuda 11.8 and so on. Change to fit your Cuda version.

re installing torch in of itself doesn't fix the issue alone, i also have to re install graphics drivers every time as well to get the program to fucntion
