### ISSUE TITLE
I'm getting this error here, can someone help me?

### ISSUE THREAD

**Issue by pjixel** [ogkalu2/comic-translate#37]
C:\comic-translate-main>python comic.py
Traceback (most recent call last):
  File "C:\comic-translate-main\comic.py", line 1, in <module>
    import dearpygui.dearpygui as dpg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\dearpygui\dearpygui.py", line 22, in <module>
    import dearpygui._dearpygui as internal_dpg
ImportError: DLL load failed while importing _dearpygui: The specified module could not be found.

C:\comic-translate-main>
![Untitled](https://github.com/ogkalu2/comic-translate/assets/165904819/ec330745-b574-4a76-8314-7531262feba6)

**Comment by kaniatwo** [comment]
yeah me too python comic.py give a error
