### ISSUE TITLE
error when translating

### ISSUE THREAD

**Issue by ztench** [ogkalu2/comic-translate#39]
Last progress at Formando bloques de texto. Imagen 1 de 36
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\prueba\comic-translate\pipeline.py", line 33, in run
    self._target(*self._args, **self._kwargs)
  File "C:\prueba\comic-translate\pipeline.py", line 249, in process
    ocr_blk_list_google(img, blk_list, google_api_key)
  File "C:\prueba\comic-translate\modules\utils\pipeline_utils.py", line 216, in ocr_blk_list_google
    y1 = text['boundingPoly']['vertices'][0]['y']
KeyError: 'y'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gueva\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\prueba\comic-translate\pipeline.py", line 36, in run
    self.error_callback(e)
  File "C:\prueba\comic-translate\pipeline.py", line 63, in error_handler
    messagebox.showerror('Error', f"{exception}.\n\nLast progress at {dpg.get_value('progress_bar_text')}")
  File "C:\Users\gueva\AppData\Local\Programs\Python\Python39\lib\tkinter\messagebox.py", line 98, in showerror
    return _show(title, message, ERROR, OK, **options)
  File "C:\Users\gueva\AppData\Local\Programs\Python\Python39\lib\tkinter\messagebox.py", line 76, in _show
    res = Message(**options).show()
  File "C:\Users\gueva\AppData\Local\Programs\Python\Python39\lib\tkinter\commondialog.py", line 42, in show
    w = Frame(self.master)
  File "C:\Users\gueva\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 3124, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "C:\Users\gueva\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
RuntimeError: main thread is not in main loop

**Comment by kaniatwo** [comment]
me too

**Comment by TeleSmsng** [comment]
Same here:
An Error occurred: 'responses'.

Last progress at Forming TextBlocks. Image 1 of 1
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\comic-translate\pipeline.py", line 34, in run
    self._target(*self._args, **self._kwargs)
  File "C:\comic-translate\pipeline.py", line 266, in process
    ocr_blk_list_google(img, blk_list, google_api_key)
  File "C:\comic-translate\modules\utils\pipeline_utils.py", line 167, in ocr_blk_list_google
    texts = result['responses'][0]['textAnnotations']
KeyError: 'responses'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\comic-translate\pipeline.py", line 37, in run
    self.error_callback(e)
  File "C:\comic-translate\pipeline.py", line 64, in error_handler
    messagebox.showerror('Error', f"{exception}.\n\nLast progress at {dpg.get_value('progress_bar_text')}")
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\tkinter\messagebox.py", line 98, in showerror
    return _show(title, message, ERROR, OK, **options)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\tkinter\messagebox.py", line 76, in _show
    res = Message(**options).show()
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\tkinter\commondialog.py", line 42, in show
    w = Frame(self.master)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 3124, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
RuntimeError: main thread is not in main loop
